services:
  dbms:
    image: postgres:16.1
    environment:
      TZ: ${OS_TIMEZONE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U ${DB_USER}"]
      interval: 1s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT}:5432
